version: '3'

name: "Docker-Handler-MicroServices"

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    build: ./../client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./../client-gateway/src:/usr/src/app/src
    command: npm run dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
  
  products-ms:
    build: ./../products-ms
    volumes:
      - ./../products-ms/src:/usr/src/app/src
    command: npm run dev
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - DATABASE_URL=${PRODUCTS_MS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222
  
  orders-db:
    container_name: orders_databases
    image: postgres:16.2
    volumes:
      - ./../orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - ${ORDERS_DB_POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${ORDERS_DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDERS_DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDERS_DB_POSTGRES_DB}
  
  orders-ms:
    depends_on:
      - orders-db
    build: ./../orders-ms
    volumes:
      - ./../orders-ms/src:/usr/src/app/src
    command: npm run dev
    environment:
      - PORT=${ORDERS_MS_PORT}
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222

  payments-ms:
    build: ./../payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    volumes:
      - ./../payments-ms/src:/usr/src/app/src
    command: npm run dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - ENDPOINT_SECRET=${ENDPOINT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCELLED_URL=${CANCELLED_URL}
      - ENDPOINT_SECRET=${ENDPOINT_SECRET}
      - NATS_SERVERS=nats://nats-server:4222

  auth-db:
    image: mongo:7
    container_name: auth_mongodb
    ports:
      - "${AUTH_MONGODB_PORT}:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - auth_mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    
  auth-ms:
    build: ./../auth-ms
    depends_on:
      - auth-db
    volumes:
      - ./../auth-ms/src:/usr/src/app/src
    command: npm run dev
    environment:
      - PORT=${AUTH_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=mongodb://auth-db:27017/users?replicaSet=rs0
      - SECRET_KEY=${AUTH_SECRET_KEY}

volumes:
  auth_mongo_data: